POST http://localhost:8080/api/users
Accept: application/json
Content-Type: application/json

{
    "username":"amunoz3",
    "name":"Alejandro3",
    "password":"password"
}

###

GET http://localhost:8080/api/users
Accept: application/json

###

GET http://localhost:8080/api/users/1
Accept: application/json

###

GET http://localhost:8080/api/users/filter/amunoz
Accept: application/json

###


GET http://localhost:8080/api/users/1/4
Accept: application/json